### ISSUE TITLE
ASM Bytecode Outline 不支持 Kotlin，ASM能对Kotlin插桩吗？

### ISSUE THREAD

**Issue by dhh-io** [AndroidAdvanceWithGeektime/Chapter-ASM#2]
源代码用Kotlin写的话，ASM能支持插桩吗？

**Comment by dhh-io** [comment]
已经尝试，可以按照Java的插桩方式，对Kotlin插桩，javassist也可以对kotlin插桩，插入的方式也是安装Java代码写，不能用kotlin的语法糖写

**Comment by qinhehu** [comment]
https://plugins.jetbrains.com/plugin/14860-asm-bytecode-viewer-support-kotlin 支持查看kotlin生成的ASM code

**Comment by hyhyhykw** [comment]
> https://plugins.jetbrains.com/plugin/14860-asm-bytecode-viewer-support-kotlin 支持查看kotlin生成的ASM code

android studio 4.0.1 使用这个会闪退

**Comment by qinhehu** [comment]
> > https://plugins.jetbrains.com/plugin/14860-asm-bytecode-viewer-support-kotlin 支持查看kotlin生成的ASM code
> 
> android studio 4.0.1 使用这个会闪退

我看看

**Comment by jiafeimao-gjf** [comment]
> 已经尝试，可以按照Java的插桩方式，对Kotlin插桩，javassist也可以对kotlin插桩，插入的方式也是安装Java代码写，不能用kotlin的语法糖写

插入的方式也是安装Java代码写，不能用kotlin的语法糖写：插桩代码必须用Java？还是插入点必须用Java

**Comment by viakiba** [comment]
> > 已经尝试，可以按照Java的插桩方式，对Kotlin插桩，javassist也可以对kotlin插桩，插入的方式也是安装Java代码写，不能用kotlin的语法糖写
> 
> 插入的方式也是安装Java代码写，不能用kotlin的语法糖写：插桩代码必须用Java？还是插入点必须用Java

需要插入的代码换成java语法写
